# (CodeBuild instructions)
version: 0.2

# Environment configuration
env:
  variables: PYTHON_VERSION:"3.11"

phases:
  # Install dependencies phase
  install:
    runtime-versions: python:3.12
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

  # Pre-build phase (run tests)
  pre_build:
    commands:
      - echo "Running tests..."
      - pytest tests/ -v --tb=short
      - echo "Tests passed! ✅"

  # Build phase (package lambda function)
  build:
    commands:
      - echo "Packaging Lambda function..."
      - mkdir -p build
      - pip install -r requirements.txt -t build/
      - cp -r app build/
      - cd build
      - zip -r ../lambda-package.zip
      - cd ..
      - echo "Lambda package created!"

  # Post-build phase
  post_build:
    commands:
      - echo "Build completed successfully! ✅"
      - ls -lh lambda-package.zip

artifacts:
  files:
    - lambda-package.zip
    - appspec-lambda.yaml
  name: BuildArtifact

cache:
  paths:
    - "/root/.cache/pip/**/*"
