AWSTemplateFormatVersion: "2010-09-09"

Description: "IAM Roles for Student Enrollment API CI/CD Pipeline"

Resources:
  # CodeBuild Service Role
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: StudentEnrollmentCodeBuildRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com

            Action: "sts:AssumeRole"

      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess"

      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "s3:GetObject"

                  - "s3:PutObject"

                  - "s3:GetBucketLocation"

                Resource:
                  - !Sub "arn:aws:s3:::student-enrollment-pipeline-artifacts-${AWS::AccountId}/*"

                  - !Sub "arn:aws:s3:::student-enrollment-pipeline-artifacts-${AWS::AccountId}"

  # CodePipeline Service Role
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: StudentEnrollmentCodePipelineRole

      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com

            Action: "sts:AssumeRole"

      Policies:
        - PolicyName: CodePipelinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # S3 permissions
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:PutObject"
                Resource:
                  - !Sub "arn:aws:s3:::student-enrollment-pipeline-artifacts-${AWS::AccountId}/*"
              # CodeBuild permissions
              - Effect: Allow
                Action:
                  - "codebuild:BatchGetBuilds"
                  - "codebuild:StartBuild"

                Resource: "*"

              # Rule 3: CodeDeploy permissions
              - Effect: Allow
                Action:
                  - "codedeploy:CreateDeployment"

                  - "codedeploy:GetDeployment"

                  - "codedeploy:GetDeploymentConfig"

                  - "codedeploy:GetApplicationRevision"

                  - "codedeploy:RegisterApplicationRevision"

                Resource: "*"

              # GitHub connection permissions
              - Effect: Allow
                Action:
                  - "codestar-connections:UseConnection"

                Resource: "*"

              # Lambda permissions
              - Effect: Allow
                Action:
                  - "lambda:InvokeFunction"

                  - "lambda:ListFunctions"

                Resource: "*"

  # 3️⃣ Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: StudentEnrollmentLambdaRole

      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"

      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # CloudWatch Logs permissions
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"

  # 4️⃣ CodeDeploy Service Role
  CodeDeployServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: StudentEnrollmentCodeDeployRole

      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codedeploy.amazonaws.com
            Action: "sts:AssumeRole"

      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSCodeDeployRoleForLambda"

Outputs:
  CodeBuildRoleArn:
    Description: CodeBuild Service Role ARN

    Value: !GetAtt CodeBuildServiceRole.Arn

    Export:
      Name: StudentEnrollment-CodeBuildRole

  CodePipelineRoleArn:
    Description: CodePipeline Service Role ARN
    Value: !GetAtt CodePipelineServiceRole.Arn
    Export:
      Name: StudentEnrollment-CodePipelineRole

  LambdaRoleArn:
    Description: Lambda Execution Role ARN
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: StudentEnrollment-LambdaRole

  CodeDeployRoleArn:
    Description: CodeDeploy Service Role ARN
    Value: !GetAtt CodeDeployServiceRole.Arn
    Export:
      Name: StudentEnrollment-CodeDeployRole
